/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liba;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatSpacegrayIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialOceanicIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightIJTheme;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author karnarajbanshi
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
    // UIManager.setLookAndFeel( new FlatLightLaf() );      //setting newLightLaf theme  //comment this part of code to disable the theme
        initComponents();
        showDate();
        showTime();
        Connect();
    }
     Connection con;
    PreparedStatement pst;
     void showDate(){
         SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
         Date d=new Date();
         Date.setText(s.format(d));
     }
      void showTime(){ //for timer we haveimported java.swing.Timer 
          new Timer(0, (ActionEvent e) -> {
              //lamba expression
              SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
              Date d=new Date();
              String dt=String.valueOf(d);
              time.setText(s.format(d)); // set value of label time with realtime time
          }).start();
          
                  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shadowRenderer1 = new shadow.ShadowRenderer();
        localTime1 = new org.joda.time.LocalTime();
        jMenu1 = new javax.swing.JMenu();
        cat_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        auth_btn = new javax.swing.JButton();
        pub_btn = new javax.swing.JButton();
        bk_btn = new javax.swing.JButton();
        mem_btn = new javax.swing.JButton();
        iss_btn = new javax.swing.JButton();
        rtn_btn = new javax.swing.JButton();
        Jpanel_action = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clock2 = new clock.Clock();
        time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        txtbid = new javax.swing.JTextField();
        txtblock = new javax.swing.JTextField();
        txtrow = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminPanel = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Defaultitem = new javax.swing.JMenu();
        light = new javax.swing.JRadioButtonMenuItem();
        dark = new javax.swing.JRadioButtonMenuItem();
        githublight = new javax.swing.JRadioButtonMenuItem();
        githubdark = new javax.swing.JRadioButtonMenuItem();
        dracula = new javax.swing.JRadioButtonMenuItem();
        intellij = new javax.swing.JRadioButtonMenuItem();
        solarizedlight = new javax.swing.JRadioButtonMenuItem();
        norddark = new javax.swing.JRadioButtonMenuItem();
        moonlight = new javax.swing.JRadioButtonMenuItem();
        oceanblue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        uguide = new javax.swing.JMenuItem();
        technicalsprt = new javax.swing.JMenuItem();
        bug = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        aboutdev = new javax.swing.JMenuItem();
        license = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        happy = new javax.swing.JMenuItem();
        loved = new javax.swing.JMenuItem();
        improvise = new javax.swing.JMenuItem();
        sad = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bookstack");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        setIconImages(null);
        setName("Main Window"); // NOI18N

        cat_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cat_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_category_48.png"))); // NOI18N
        cat_btn.setText(" Category");
        cat_btn.setBorder(new com.formdev.flatlaf.ui.FlatRoundBorder());
        cat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_btnActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_logout_rounded_left_48.png"))); // NOI18N
        jButton2.setText("  Logout        ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        auth_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        auth_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_oscar_wilde_48.png"))); // NOI18N
        auth_btn.setText(" Author     ");
        auth_btn.setActionCommand("  Author     ");
        auth_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auth_btnActionPerformed(evt);
            }
        });

        pub_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pub_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_bookshop_48.png"))); // NOI18N
        pub_btn.setText(" Publisher    ");
        pub_btn.setToolTipText("");
        pub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pub_btnActionPerformed(evt);
            }
        });

        bk_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bk_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_book_48.png"))); // NOI18N
        bk_btn.setText(" Book        ");
        bk_btn.setActionCommand("  Book        ");
        bk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bk_btnActionPerformed(evt);
            }
        });

        mem_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mem_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_people_48.png"))); // NOI18N
        mem_btn.setText("  Member  ");
        mem_btn.setActionCommand(" Member  ");
        mem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_btnActionPerformed(evt);
            }
        });

        iss_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iss_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_return_book_48.png"))); // NOI18N
        iss_btn.setText("Issue Book ");
        iss_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iss_btnActionPerformed(evt);
            }
        });

        rtn_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtn_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_borrow_book_48.png"))); // NOI18N
        rtn_btn.setText("Return Book");
        rtn_btn.setActionCommand("Return Book ");
        rtn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtn_btnActionPerformed(evt);
            }
        });

        Jpanel_action.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true), "DASHBOARD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 204, 255))); // NOI18N
        Jpanel_action.setName("action_window"); // NOI18N
        Jpanel_action.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        clock2.setName("Bookstack Clock"); // NOI18N

        time.setFont(new java.awt.Font("Museo Sans 500", 0, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("Your TIme");
        time.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(clock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(clock2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        Date.setFont(new java.awt.Font("Museo Sans 500", 0, 18)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date.setText("Your Date");
        Date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jCalendar1.setBorder(new com.formdev.flatlaf.ui.FlatDropShadowBorder());
        jCalendar1.setFont(new java.awt.Font("Museo Sans 500", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)), "Qucik Locate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Nova Light", 1, 12), new java.awt.Color(0, 204, 255))); // NOI18N

        txtbid.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtbid.setText("ID");
        txtbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbidActionPerformed(evt);
            }
        });
        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbidKeyPressed(evt);
            }
        });

        txtblock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtblock.setText("block");

        txtrow.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtrow.setText("row");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_access_32.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_search_property_32.png"))); // NOI18N
        jButton1.setText("Locate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_columns_32.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_rows_32.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_abc_32.png"))); // NOI18N

        txtbname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtbname.setText("Bookname");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtbid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtblock, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtblock)
                        .addComponent(txtrow)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Jpanel_actionLayout = new javax.swing.GroupLayout(Jpanel_action);
        Jpanel_action.setLayout(Jpanel_actionLayout);
        Jpanel_actionLayout.setHorizontalGroup(
            Jpanel_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_actionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Jpanel_actionLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Jpanel_actionLayout.setVerticalGroup(
            Jpanel_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_actionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_actionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\colorful icon\\icons8_book_stack_48.png")); // NOI18N
        jLabel2.setText("  Bookstack: Library Software");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Developed by: Karna Rajbanshi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setFocusCycleRoot(true);

        adminPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\colorful icon\\gears_20px.png")); // NOI18N
        adminPanel.setText("Setting");
        adminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPanelActionPerformed(evt);
            }
        });
        adminPanel.add(jSeparator2);

        Defaultitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/icons8_change_theme_16.png"))); // NOI18N
        Defaultitem.setText("Themes");

        light.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        light.setText("Light");
        light.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightActionPerformed(evt);
            }
        });
        Defaultitem.add(light);

        dark.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        dark.setText("Dark");
        dark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkActionPerformed(evt);
            }
        });
        Defaultitem.add(dark);

        githublight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        githublight.setText("GitHub light");
        githublight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githublightActionPerformed(evt);
            }
        });
        Defaultitem.add(githublight);

        githubdark.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        githubdark.setText("GitHub Dark");
        githubdark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubdarkActionPerformed(evt);
            }
        });
        Defaultitem.add(githubdark);

        dracula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        dracula.setText("Dracula");
        dracula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                draculaActionPerformed(evt);
            }
        });
        Defaultitem.add(dracula);

        intellij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        intellij.setText("Intellij");
        intellij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intellijActionPerformed(evt);
            }
        });
        Defaultitem.add(intellij);

        solarizedlight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        solarizedlight.setText("Spacegray");
        solarizedlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solarizedlightActionPerformed(evt);
            }
        });
        Defaultitem.add(solarizedlight);

        norddark.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        norddark.setText("Nord Dark");
        norddark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norddarkActionPerformed(evt);
            }
        });
        Defaultitem.add(norddark);

        moonlight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        moonlight.setText("Moonlight");
        moonlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moonlightActionPerformed(evt);
            }
        });
        Defaultitem.add(moonlight);

        oceanblue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        oceanblue.setText("Ocean Blue");
        oceanblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oceanblueActionPerformed(evt);
            }
        });
        Defaultitem.add(oceanblue);

        adminPanel.add(Defaultitem);
        adminPanel.add(jSeparator1);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/database_administrator_20px.png"))); // NOI18N
        jMenuItem8.setText("Admin panel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        adminPanel.add(jMenuItem8);

        jMenuBar1.add(adminPanel);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/help_20px.png"))); // NOI18N
        help.setText("Help!");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        uguide.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        uguide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/user_manual_20px.png"))); // NOI18N
        uguide.setText("User's Guide");
        uguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uguideActionPerformed(evt);
            }
        });
        help.add(uguide);

        technicalsprt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        technicalsprt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/technical_support_20px.png"))); // NOI18N
        technicalsprt.setText("Technical support");
        technicalsprt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                technicalsprtMouseClicked(evt);
            }
        });
        technicalsprt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicalsprtActionPerformed(evt);
            }
        });
        help.add(technicalsprt);

        bug.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        bug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/bug_20px.png"))); // NOI18N
        bug.setText("Report bug");
        bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugActionPerformed(evt);
            }
        });
        help.add(bug);

        jMenuBar1.add(help);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/about_20px.png"))); // NOI18N
        about.setText("About");

        aboutdev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/developer_20px.png"))); // NOI18N
        aboutdev.setText("About Developer");
        aboutdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutdevActionPerformed(evt);
            }
        });
        about.add(aboutdev);

        license.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/agreement_20px.png"))); // NOI18N
        license.setText("License agreement");
        license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseActionPerformed(evt);
            }
        });
        about.add(license);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\colorful icon\\feedback_20px.png")); // NOI18N
        jMenu4.setText("Feedback");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        happy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/happy_25px.png"))); // NOI18N
        happy.setText("The software is useful");
        happy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                happyActionPerformed(evt);
            }
        });
        jMenu4.add(happy);

        loved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/love_25px.png"))); // NOI18N
        loved.setText("I loved the software");
        loved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lovedActionPerformed(evt);
            }
        });
        jMenu4.add(loved);

        improvise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/improvement_25px.png"))); // NOI18N
        improvise.setText("Need some improvement");
        improvise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                improviseActionPerformed(evt);
            }
        });
        jMenu4.add(improvise);

        sad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/liba/sad_25px.png"))); // NOI18N
        sad.setText("Not useful at all");
        sad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadActionPerformed(evt);
            }
        });
        jMenu4.add(sad);

        about.add(jMenu4);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(rtn_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iss_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mem_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bk_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pub_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(auth_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cat_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jpanel_action, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(auth_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iss_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(rtn_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jpanel_action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/slibr","root","");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Publisher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     
    private void pub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pub_btnActionPerformed
        // TODO add your handling code here:
////        
          Publisher c = new Publisher();
        c.setVisible(true);
        
        
    }//GEN-LAST:event_pub_btnActionPerformed
//

    
    
    
    
 //   
    private void cat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_btnActionPerformed
        // TODO add your handling code here:
        
        category1 c = new category1();
        c.setVisible(true);
        
        
        
    }//GEN-LAST:event_cat_btnActionPerformed

    private void auth_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auth_btnActionPerformed
        // TODO add your handling code here:
          author c = new author();
        c.setVisible(true);
        
        
        
    }//GEN-LAST:event_auth_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        this.setVisible(false);
        l.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bk_btnActionPerformed
        // TODO add your handling code here:
        Book1 b1=new Book1();
        b1.setVisible(true);
    }//GEN-LAST:event_bk_btnActionPerformed

    private void mem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_btnActionPerformed
        // TODO add your handling code here:
          Member c = new Member();
          c.setVisible(true);
        
    }//GEN-LAST:event_mem_btnActionPerformed

    private void iss_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iss_btnActionPerformed
        // TODO add your handling code here:
        
         Lend c = new Lend();
          c.setVisible(true);
        
        
    }//GEN-LAST:event_iss_btnActionPerformed

    private void rtn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtn_btnActionPerformed
        // TODO add your handling code here:
         Return c = new Return();
          c.setVisible(true);
        
        
        
    }//GEN-LAST:event_rtn_btnActionPerformed

    private void uguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uguideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uguideActionPerformed

    private void technicalsprtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicalsprtActionPerformed
        // TODO add your handling code here:
         Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI("http://karnarajbanshi.wordpress.com/"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_technicalsprtActionPerformed

    private void bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugActionPerformed
        // TODO add your handling code here:
         Desktop desktop = Desktop.getDesktop();

        try {
            // Open user-default mail client application.
            desktop.mail();
        } catch (IOException e) {
        }

        try {
           // Open user-default mail client with the email message fields information.
            String message = "mailto:karnaraj05@gmail.com?cc=&subject=Report_Bug&body=";
            URI uri = URI.create(message);
            desktop.mail(uri);
        } catch (IOException e) {
        }
        
    }//GEN-LAST:event_bugActionPerformed

    private void aboutdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutdevActionPerformed
        // TODO add your handling code here:
                  
    }//GEN-LAST:event_aboutdevActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_helpActionPerformed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_helpMouseClicked

    private void technicalsprtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_technicalsprtMouseClicked
        // TODO add your handling code here:
           Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI("https://karnarajbanshi.wordpress.com/"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_technicalsprtMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        Master_Login login =new Master_Login();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void txtbidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String id = txtbid.getText();
            try {
                pst = con.prepareStatement("SELECT block,row,bname FROM book where id=?");
                  pst.setString(1,id);
                ResultSet rs = pst.executeQuery();
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"Book ID not Found");
                }
                else
                {
                    String blockno = rs.getString("block");
                     String rowno = rs.getString("row");
                     String bookn= rs.getString("bname");
                      txtblock.setText(blockno);
                     txtrow.setText(rowno);  
                     txtbname.setText(bookn);
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
   
    }//GEN-LAST:event_txtbidKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = txtbid.getText();
            try {
                pst = con.prepareStatement("SELECT block,row,bname FROM book where id=?");
                  pst.setString(1,id);
                ResultSet rs = pst.executeQuery();
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"Book ID not Found");
                }
                else
                {
                    String blockno = rs.getString("block");
                    String rowno = rs.getString("row");
                    String bookn= rs.getString("bname");
                    txtblock.setText(blockno);
                    txtrow.setText(rowno);                 
                    txtbname.setText(bookn);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbidActionPerformed

    private void licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseActionPerformed
        // TODO add your handling code here:
        License lic;
        lic=new License();
        lic.setVisible(true);
    }//GEN-LAST:event_licenseActionPerformed

    private void improviseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_improviseActionPerformed
        // TODO add your handling code here:
         Desktop desktop = Desktop.getDesktop();

        try {
            // Open user-default mail client application.
            desktop.mail();
        } catch (IOException e) {
        }

        try {
           // Open user-default mail client with the email message fields information.
            String message = "mailto:karnaraj05@gmail.com?cc=&subject=Feedback&body=The_software_need_some_improvement.";
            URI uri = URI.create(message);
            desktop.mail(uri);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_improviseActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void happyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_happyActionPerformed
        // TODO add your handling code here:
          Desktop desktop = Desktop.getDesktop();

        try {
            // Open user-default mail client application.
            desktop.mail();
        } catch (IOException e) {
        }

        try {
           // Open user-default mail client with the email message fields information.
            String message = "mailto:karnaraj05@gmail.com?cc=&subject=Feedback&body=The_software_is_useful";
            URI uri = URI.create(message);
            desktop.mail(uri);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_happyActionPerformed

    private void lovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lovedActionPerformed
        // TODO add your handling code here:
         Desktop desktop = Desktop.getDesktop();

        try {
            // Open user-default mail client application.
            desktop.mail();
        } catch (IOException e) {
        }

        try {
           // Open user-default mail client with the email message fields information.
            String message = "mailto:karnaraj05@gmail.com?cc=&subject=Feedback&body=I_loved_the_software.";
            URI uri = URI.create(message);
            desktop.mail(uri);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lovedActionPerformed

    private void sadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadActionPerformed
        // TODO add your handling code here:
         Desktop desktop = Desktop.getDesktop();

        try {
            // Open user-default mail client application.
            desktop.mail();
        } catch (IOException e) {
        }

        try {
           // Open user-default mail client with the email message fields information.
            String message = "mailto:karnaraj05@gmail.com?cc=&subject=Feedback&body=The_software_is_not_useful_at_all.";
            URI uri = URI.create(message);
            desktop.mail(uri);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_sadActionPerformed

    private void githublightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githublightActionPerformed
        // TODO add your handling code here:
               
                 try {
    UIManager.setLookAndFeel( new FlatGitHubIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}
            Main m=new Main();
            m.setVisible(true); 
            this.dispose();
    }//GEN-LAST:event_githublightActionPerformed

    private void lightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightActionPerformed
        // TODO add your handling code here:
              
            try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        Main m=new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lightActionPerformed

    private void darkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkActionPerformed
        // TODO add your handling code here:
     
            try {
    UIManager.setLookAndFeel( new FlatDarkLaf() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_darkActionPerformed

    private void intellijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intellijActionPerformed
        // TODO add your handling code here:
         
            try {
    UIManager.setLookAndFeel( new FlatIntelliJLaf() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_intellijActionPerformed

    private void draculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_draculaActionPerformed
        // TODO add your handling code here:
         
            try {
    UIManager.setLookAndFeel( new FlatDraculaIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_draculaActionPerformed

    private void githubdarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubdarkActionPerformed
        // TODO add your handling code here:
        
            try {
    UIManager.setLookAndFeel( new FlatGitHubDarkIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
 this.dispose();
 
    }//GEN-LAST:event_githubdarkActionPerformed

    private void solarizedlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solarizedlightActionPerformed
        // TODO add your handling code here:
          // this.dispose();
                 try {
    UIManager.setLookAndFeel( new FlatSpacegrayIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}
          Main m=new Main();
        
          m.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_solarizedlightActionPerformed

    private void norddarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norddarkActionPerformed
        // TODO add your handling code here:
        
            try {
    UIManager.setLookAndFeel( new FlatNordIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_norddarkActionPerformed

    private void moonlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moonlightActionPerformed
        // TODO add your handling code here:
        
            try {
    UIManager.setLookAndFeel( new FlatMoonlightIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_moonlightActionPerformed

    private void oceanblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oceanblueActionPerformed
        // TODO add your handling code here:
         
            try {
    UIManager.setLookAndFeel( new FlatMaterialOceanicIJTheme() );
} catch( UnsupportedLookAndFeelException ex ) {
    System.err.println( "Failed to initialize LaF" );
}

Main m=new Main();
m.setVisible(true);
this.dispose();
    }//GEN-LAST:event_oceanblueActionPerformed

    private void adminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPanelActionPerformed
        // TODO add your handling code here:
        AdminDashboard admin = new AdminDashboard();
        admin.setVisible(true);
        
    }//GEN-LAST:event_adminPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String themename="Windows";
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (themename.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JMenu Defaultitem;
    private javax.swing.JPanel Jpanel_action;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem aboutdev;
    private javax.swing.JMenu adminPanel;
    private javax.swing.JButton auth_btn;
    private javax.swing.JButton bk_btn;
    private javax.swing.JMenuItem bug;
    private javax.swing.JButton cat_btn;
    private clock.Clock clock2;
    private javax.swing.JRadioButtonMenuItem dark;
    private javax.swing.JRadioButtonMenuItem dracula;
    private javax.swing.JRadioButtonMenuItem githubdark;
    private javax.swing.JRadioButtonMenuItem githublight;
    private javax.swing.JMenuItem happy;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem improvise;
    private javax.swing.JRadioButtonMenuItem intellij;
    private javax.swing.JButton iss_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem license;
    private javax.swing.JRadioButtonMenuItem light;
    private org.joda.time.LocalTime localTime1;
    private javax.swing.JMenuItem loved;
    private javax.swing.JButton mem_btn;
    private javax.swing.JRadioButtonMenuItem moonlight;
    private javax.swing.JRadioButtonMenuItem norddark;
    private javax.swing.JRadioButtonMenuItem oceanblue;
    private javax.swing.JButton pub_btn;
    private javax.swing.JButton rtn_btn;
    private javax.swing.JMenuItem sad;
    private shadow.ShadowRenderer shadowRenderer1;
    private javax.swing.JRadioButtonMenuItem solarizedlight;
    private javax.swing.JMenuItem technicalsprt;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtblock;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtrow;
    private javax.swing.JMenuItem uguide;
    // End of variables declaration//GEN-END:variables
}
